<a href="https://colab.research.google.com/github/OMatheusWander/Cienciadedadosparaeconomistas/blob/main/stata_aula1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOxLpovGC+ODDd9qB2oAovE",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/OMatheusWander/BrasilAPI/blob/master/AULA_DE_STATA.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "SJEnsThz_gzm"
      },
      "outputs": [],
      "source": [
        "\n",
        "forvalues i = 5/11 {\n",
        " cls\n",
        " clear all\n",
        " import delimited C:\\Users\\06592896957\\Desktop\\PNAD_COVID_`i'.csv, clear\n",
        " keep if uf == 42\n",
        " keep if v1022 == 1\n",
        " keep if v1023 == 1\n",
        " save C:\\Users\\06592896957\\Desktop\\PNAD_COVID_`i'.dta, replace\n",
        "}\n",
        "\n",
        "cls\n",
        "clear all\n",
        "use C:\\Users\\Usuario\\Seafile\\Seafile\\stuffs\\exercises\\ler_microdados\\PNAD_COVID_5.dta\n",
        "forvalues i = 6/11 {\n",
        " append using C:\\Users\\Usuario\\Seafile\\Seafile\\stuffs\\exercises\\ler_microdados\\PNAD_COVID_`i'.dta\n",
        " save C:\\Users\\Usuario\\Seafile\\Seafile\\stuffs\\exercises\\ler_microdados\\data_COVID.dta, replace\n",
        "}\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "*note que são só entrevistas em Floripa\n",
        "tab rm_ride capital\n",
        "*note o número de entrevistados por mês e semana\n",
        "tab v1012 v1013\n",
        "export excel using \"C:\\Users\\Usuario\\Seafile\\Seafile\\stuffs\\exercises\\ler_microdados\\data_COVID.xlsx\", firstrow(variables) replace\n",
        "\n",
        "\n",
        "cls\n",
        "clear all\n",
        "use C:\\Users\\Usuario\\Seafile\\Seafile\\stuffs\\exercises\\ler_microdados\\data_COVID.dta\n",
        "\n",
        "egen id = group(v1008 estrato upa)\n",
        "rename v1013 mes\n",
        "\n",
        "keep if a001a == 1\n",
        "\n",
        "sort id mes\n",
        "bysort id: gen times = _N\n",
        "\n",
        "tab times\n",
        "\n",
        "drop if times == 1\n",
        "\n",
        "rename a002 idade\n",
        "\n",
        "gen homem = cond(a003 == 1, 1, 0)\n",
        "\n",
        "*tw (kdensity idade if homem == 0) (kdensity idade if homem == 1)\n",
        "\n",
        "gen branco = cond(a004 == 1, 1, 0)\n",
        "\n",
        "rename a005 edu\n",
        "\n",
        "tab edu, m\n",
        "\n",
        "rename c008 horas\n",
        "rename c01012 w\n",
        "\n",
        "order id mes idade homem branco edu horas w\n",
        "\n",
        "drop ano-times\n",
        "\n",
        "gen lnw = ln(w)\n",
        "\n",
        "sort id mes\n",
        "\n",
        "tsset id mes\n",
        "tsfill, full\n",
        "\n",
        "bysort id: gen ok = cond(_n == 1 & idade != . & homem != . & branco != . & edu!=1,1,0)\n",
        "bysort id: replace ok = ok[_n-1] if _n > 1\n",
        "drop if ok == 0\n",
        "drop ok\n",
        "\n",
        "bysort id: egen idade2 = max(idade)\n",
        "drop if idade2 == .\n",
        "bysort id: gen ok = cond(idade == . | idade == idade2 | idade == idade2-1 ,1,0)\n",
        "bysort id: egen ok2 = mean(ok)\n",
        "drop if ok2 != 1\n",
        "drop ok ok2 idade2\n",
        "\n",
        "bysort id: replace idade = idade[_n-1] if idade == .\n",
        "\n",
        "bysort id: replace homem = homem[_n-1] if homem == .\n",
        "bysort id: egen homem2 = mean(homem)\n",
        "drop if homem != homem2\n",
        "drop homem2\n",
        "\n",
        "bysort id: replace branco = branco[_n-1] if branco == .\n",
        "bysort id: egen branco2 = mean(branco)\n",
        "drop if branco != branco2\n",
        "drop branco2\n",
        "\n",
        "bysort id: egen edu2 = max(edu)\n",
        "drop if edu2 == .\n",
        "bysort id: gen ok = cond(edu == . | edu == edu2 | edu == edu2-1 ,1,0)\n",
        "bysort id: egen ok2 = mean(ok)\n",
        "drop if ok2 != 1\n",
        "drop ok ok2 edu2\n",
        "\n",
        "sort id mes\n",
        "\n",
        "tsset id mes\n",
        "tsfill, full\n",
        "\n",
        "xtset id mes\n",
        "gen idade2 = idade^2\n",
        "xtreg lnw idade idade2 i.edu, fe\n",
        "\n"
      ]
    }
  ]
}